import type { Metadata } from "next";
import { Inter, Marck_Script } from "next/font/google";
import HeartEffect from "../ui/HeartEffect";
import "./globals.css";
const inter = Inter({
  subsets: ["latin", "cyrillic"],
});
const marckScript = Marck_Script({
  subsets: ["latin", "cyrillic"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${marckScript.className}`}>
        {children}
        <HeartEffect />
      </body>
    </html>
  );
}
